# Generated by Django 3.1.3 on 2020-11-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_id', models.IntegerField(default=0)),
                ('w_timu', models.CharField(max_length=8)),
                ('w_daan', models.TextField()),
                ('w_jiexi_lei', models.CharField(max_length=8)),
                ('w_jiexi', models.TextField()),
                ('w_shijuan_lei', models.CharField(max_length=20)),
                ('w_shiti_lei', models.CharField(max_length=10)),
                ('w_quyu', models.CharField(max_length=20)),
                ('w_nian', models.IntegerField(default=2020)),
                ('w_nandu', models.IntegerField(default=3)),
                ('w_zhiliang', models.IntegerField(default=3)),
                ('w_zhishidian', models.CharField(max_length=40)),
                ('w_guanjianci', models.CharField(max_length=30)),
            ],
        ),
    ]
