# Generated by Django 3.1.7 on 2021-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiti',
            name='w_zhishidian',
        ),
        migrations.AddField(
            model_name='shiti',
            name='w_zhishidian1',
            field=models.CharField(default='01010101', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiti',
            name='w_zhishidian2',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='shiti',
            name='w_zhishidian3',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
