# Generated by Django 3.1.7 on 2021-03-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiti', '0002_auto_20210310_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiti',
            name='w_zhishidian1',
        ),
        migrations.RemoveField(
            model_name='shiti',
            name='w_zhishidian2',
        ),
        migrations.RemoveField(
            model_name='shiti',
            name='w_zhishidian3',
        ),
        migrations.AddField(
            model_name='shiti',
            name='w_zhishidian',
            field=models.CharField(default='', max_length=50),
        ),
    ]
