# Generated by Django 3.1.7 on 2021-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiti', '0003_auto_20210311_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiti',
            name='w_jiexi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shiti',
            name='w_zhishidian',
            field=models.CharField(default='', max_length=100),
        ),
    ]
