# Generated by Django 3.2.5 on 2021-07-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiti', '0004_auto_20210311_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiti',
            name='id',
        ),
        migrations.AlterField(
            model_name='shiti',
            name='w_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
