# Generated by Django 3.0.5 on 2020-05-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaokaoBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gk_subject', models.CharField(max_length=10)),
                ('gk_type', models.CharField(max_length=20)),
                ('gk_year', models.CharField(max_length=20)),
                ('gk_name', models.CharField(max_length=100)),
                ('gk_file', models.CharField(max_length=20)),
                ('gk_file_ans', models.CharField(default='yes', max_length=5)),
                ('gk_file_rev', models.CharField(default='no', max_length=5)),
            ],
        ),
    ]
