# Generated by Django 3.0.5 on 2020-04-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DgBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dg_subject', models.CharField(max_length=10)),
                ('dg_grade', models.CharField(max_length=20)),
                ('dg_time', models.CharField(max_length=20)),
                ('dg_name', models.CharField(max_length=100)),
                ('dg_file', models.CharField(max_length=10)),
                ('dg_file_ans', models.CharField(default='yes', max_length=5)),
                ('dg_file_rev', models.CharField(default='no', max_length=5)),
            ],
        ),
    ]
