# Generated by Django 3.0.3 on 2020-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=10)),
                ('exam_loc', models.CharField(max_length=10)),
                ('exam_time', models.CharField(max_length=10)),
                ('exam_grade', models.CharField(max_length=20)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_file', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
