# Generated by Django 3.0.5 on 2020-04-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20200225_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exambank',
            old_name='exam_file',
            new_name='ex_file',
        ),
        migrations.RenameField(
            model_name='exambank',
            old_name='exam_grade',
            new_name='ex_grade',
        ),
        migrations.RenameField(
            model_name='exambank',
            old_name='exam_loc',
            new_name='ex_loc',
        ),
        migrations.RenameField(
            model_name='exambank',
            old_name='exam_name',
            new_name='ex_name',
        ),
        migrations.RenameField(
            model_name='exambank',
            old_name='exam_time',
            new_name='ex_type',
        ),
        migrations.RemoveField(
            model_name='exambank',
            name='exam_type',
        ),
        migrations.AddField(
            model_name='exambank',
            name='ex_file_ans',
            field=models.CharField(default='yes', max_length=5),
        ),
        migrations.AddField(
            model_name='exambank',
            name='ex_file_rev',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='exambank',
            name='ex_time',
            field=models.CharField(default='2020', max_length=20),
            preserve_default=False,
        ),
    ]
